[package]
name = "rusty-games-signaling-server"
version = "0.1.0"
authors = ["Tomek Karwowski <to.karwowski@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.18"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"
tokio = { version = "1.14.0", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.8"
warp = "0.3.2"
simplelog = "0.8.0"
log = "0.4.8"

rusty-games-protocol = {path = "../protocol"}
