name: tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - run: cargo run &
        working-directory: ./signaling-server
      - name: Test on Firefox
        run: wasm-pack test --headless --firefox
        working-directory: ./library
        env:
          WS_IP_PORT: 127.0.0.1:9001
      - name: Test on Chrome
        run: wasm-pack test --headless --chrome
        working-directory: ./library
        env:
          WS_IP_PORT: 127.0.0.1:9001
#      - name: Check docstring compile
#         this fails with error: Can't skip running doc tests with --no-run
#         run: cargo +nightly test --doc -Zdoctest-xcompile --no-run
